In [1]:
import numpy as np 

In [17]:
a = np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4]]
              ]])


In [15]:
a.ndim

4

In [23]:
a.dtype

dtype('int64')

In [20]:
a.astype(int)

array([[[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]]])

In [26]:

a = np.linspace(1, 100 ,6)

a

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [61]:
np.random.randint(0, high=100, size=5, dtype=int)



array([24, 81, 84, 75, 84])

In [64]:
a=np.ones((3,3))

for i in a :
    print(i)

[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


In [65]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [99]:
# Create 10 evenly spaced numbers between 0 and 1 
arr2=np.linspace(5,100,10).astype(int)

arr2

array([  5,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [91]:
# Create numbers from 10 to 50 with step 5
arr1=np.arange(10 , 50 , 5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [79]:
np.random.rand(3,3)


array([[0.37099873, 0.01998712, 0.63843483],
       [0.95564745, 0.71938461, 0.68687072],
       [0.91856481, 0.94619284, 0.1003505 ]])

In [83]:
arr=np.random.randint(1,100,(5,5))

In [100]:
arr2.reshape(5,-1)

array([[  5,  15],
       [ 26,  36],
       [ 47,  57],
       [ 68,  78],
       [ 89, 100]])

In [105]:
arr1.reshape(1,-1)

array([[10, 15, 20, 25, 30, 35, 40, 45]])

## 

In [110]:
arr2.reshape(2,-1)

array([[  5,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [111]:
arr2.ravel()

array([  5,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [112]:
arr2

array([  5,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [115]:
arr2=arr2.reshape(2,-1)

In [116]:
arr2

array([[  5,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [117]:
a=arr2.flatten()

In [118]:
a

array([  5,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [119]:
arr2

array([[  5,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [127]:
a[0]=999
a

array([999,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [128]:
arr2

array([[  1,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [124]:
b = arr2.ravel()
b[0]=1
b

array([  1,  15,  26,  36,  47,  57,  68,  78,  89, 100])

In [125]:
arr2

array([[  1,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [130]:
arr = np.array([1,2,3])

np.expand_dims(arr, axis=0)

array([[1, 2, 3]])

In [131]:
np.expand_dims(arr, axis=1)


array([[1],
       [2],
       [3]])

In [132]:
arr2

array([[  1,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [166]:
arr2[1][-1]
arr2[1][2:4]
arr[:3]
arr2[1][::2]
arr2[0][::-1]
arr2[1][[0,2,3]]

array([57, 78, 89])

In [165]:
arr = np.array([10, 20, 30, 40, 50])
arr[[0, 2, 3]]# fancy indexing 


array([10, 30, 40])

In [168]:
arr[arr>5]

array([10, 20, 30, 40, 50])

In [179]:
v= np.array([1,2,2,2,2])
print(v.shape)
#shape  5, 
x=  np.array([[1,2,2,2,2,]])
x.shape #shape 1,5

(5,)


(1, 5)

In [185]:
np.cumsum(arr2).reshape(2,-1)

array([[  1,  16,  42,  78, 125],
       [182, 250, 328, 417, 517]])

In [183]:
arr2

array([[  1,  15,  26,  36,  47],
       [ 57,  68,  78,  89, 100]])

In [193]:
arr2[axis=1]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (845154396.py, line 1)

In [197]:
np.drop(arr2)

AttributeError: module 'numpy' has no attribute 'drop'

In [290]:
import numpy as np

np.random.seed(42)   # fix randomness

a = np.random.randint(1, 100, (2, 9))
print(a)


[[52 93 15 72 61 21 83 87 75]
 [75 88 24  3 22 53  2 88 30]]


In [244]:
np.random.seed(3)

In [268]:
np.random.seed(42)


In [274]:
import numpy as np

# Fix the random numbers
np.random.seed(42)

print(np.random.rand(3))
print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


In [295]:
import pandas as pd

s = pd.Series([1, 2, 3, 4])
s = pd.to_numeric(s, downcast="integer")

print(s.dtype)


int8


In [2]:
import pandas as pd

df = pd.DataFrame({
    'customer_id':[1,2,1,3,2,1,4,3],
    'order_id':[101,102,103,104,105,106,107,108],
    'order_date':['2024-01-10','2024-01-15','2024-02-05','2024-02-10',
                  '2024-02-20','2024-03-01','2024-03-05','2024-03-15'],
    'amount':[500,700,300,900,400,800,200,1000]
})

In [3]:
df = pd.DataFrame({
    "customer_id":[1,2,1,3,2,1,4,3],
    "amount":[500,700,300,900,400,800,200,1000],
    "city":["Pune","Mumbai","Pune","Delhi","Mumbai","Pune","Nagpur","Delhi"]
})