In [1]:
# create a array from 1-100
import numpy as np 
arr=np.arange(1,100)
arr





array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
# print odd  number from 1-100 
arr = np.arange(1,101,2)
print(arr)

# method 2 
arr= np.arange(1,101)
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [5]:
# print all even number from 1 - 100 
print(np.arange(2,101,1))

arr = np.arange(1,101)
print(arr[arr%2==0]) 


[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [21]:
# Write a function that takes a NumPy array of integers and returns:

# Sum of all elements
# Mean
# Maximum value
# Minimum value
# Example
# Input:
# arr = np.array([10, 20, 30, 40, 50])

# Output:
# Sum = 150
# Mean = 30.0
# Max = 50
# Min = 10
import numpy as np 
def result(arr): 
    sum_arr = np.sum(arr)
    mean_arr = np.mean(arr)
    max_arr = np.max(arr)
    min_arr = np.min(arr)
    print("sum_arr",sum_arr)
    print("mean_arr",mean_arr)
    print("max_arr",max_arr)
    print("min_arr",min_arr)
result([10, 20, 30, 40, 50])

sum_arr 150
mean_arr 30.0
max_arr 50
min_arr 10


In [23]:
# Given a NumPy array, replace all odd numbers with -1.  
arr = np.arange(1,26)
arr[arr%2!=0]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1,
       18, -1, 20, -1, 22, -1, 24, -1])

In [32]:
# Question 3: Matrix Operations (Medium)

# Problem:

# Given two 3×3 NumPy matrices, perform the following operations:

# Matrix addition
# Matrix multiplication
# Transpose of the first matrix

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
sum_matrix = A+B
mul_matrix = A@B
Trans= A.T


print("Addition:\n", sum_matrix)
print("Matrix Multiplication:\n", mul_matrix)
print("Transpose:\n",Trans)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
